#! /bin/sh
### BEGIN INIT INFO
# Provides:          tails-set-audit-log-permissions
# Required-Start:    mountkernfs $local_fs auditd
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# X-Start-Before:    $x-display-manager gdm gdm3
# Short-Description: Set more flexible permissions on audit.log
# Description:       Set more flexible permissions on audit.log
### END INIT INFO

# Author: Tails Developers <tails@boum.org>

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH="/usr/sbin:/usr/bin:/sbin:/bin"
DESC="Set more flexible permissions on audit.log"
NAME="tails-set-audit-log-permissions"
SCRIPTNAME="/etc/init.d/${NAME}"

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

do_start()
{
   chgrp auditlog /var/log/audit/audit.log
   chmod 0640     /var/log/audit/audit.log
}

case "${1}" in
  start)
	[ "${VERBOSE}" != no ] && log_daemon_msg "${DESC}" "${NAME}"
	do_start
        [ "${VERBOSE}" != no ] && log_end_msg ${?}
	;;
  restart|reload|stop|force-reload)
	:
	;;
  *)
	echo "Usage: ${SCRIPTNAME} start" >&2
	exit 1
	;;
esac

:
