#!/bin/bash

# set -x

umask 022

### functions

fatal () {
   echo "$*" >&2
   exit 1
}

### Main

# we require building from git
git rev-parse --is-inside-work-tree &> /dev/null \
   || fatal "${PWD} is not a Git tree."

. config/amnesia
if [ -e config/amnesia.local ] ; then
   . config/amnesia.local
fi

# a clean starting point
rm -rf cache/stages_rootfs

# get LB_BINARY_IMAGES
. config/binary

# get LB_ARCHITECTURES and LB_DISTRIBUTION
. config/bootstrap

# build the doc wiki
./build-wiki

# refresh translations of our programs
./refresh-translations || fatal "refresh-translations failed ($?)."

# save http_proxy if set
if [ -n "$http_proxy" ] ; then
   echo "http_proxy='$http_proxy'" >> config/environment.chroot
fi

# save variables that are needed by chroot hooks
echo "LB_DISTRIBUTION=${LB_DISTRIBUTION}" >> config/environment.chroot
echo "POTFILES_DOT_IN='$(
         /bin/grep -E --no-filename '[^ #]*\.in$' po/POTFILES.in \
       | sed -e 's,^config/includes.chroot,,' | tr "\n" ' '
   )'" \
   >> config/tails/variables

# fix permissions on some source files that will be copied as is to the chroot.
# they may be wrong, e.g. if the Git repository was cloned with a strict umask.
chmod -R go+rX config/includes.binary/
chmod -R go+rX config/includes.chroot/etc
chmod    0440  config/includes.chroot/etc/sudoers.d/*
chmod    go+rX config/includes.chroot/home
chmod    go+rX config/includes.chroot/lib
chmod    go+rX config/includes.chroot/lib/live
chmod -R go+rx config/includes.chroot/lib/live/config
chmod    go+rX config/includes.chroot/live
chmod -R go+rX config/includes.chroot/usr
chmod -R go+rx config/includes.chroot/usr/local/bin
chmod -R go+rx config/includes.chroot/usr/local/sbin
chmod -R go+rX config/includes.chroot/usr/share/doc/tails
chmod -R go+rX config/apt
chmod -R go+rX config/archives

# build the image

: ${MKSQUASHFS_OPTIONS:='-comp xz'}
export MKSQUASHFS_OPTIONS

# get git branch or tag so we can set the basename appropriately, i.e.:
# * if we build from a tag:    tails-$ARCH-$TAG.iso
# * if we build from a branch: tails-$ARCH-$BRANCH-$VERSION-$DATE.iso
# * if Jenkins builds from a branch: tails-$ARCH-$BRANCH-$VERSION-$TIME-$COMMIT.iso
if GIT_REF="$(git symbolic-ref HEAD)"; then
    GIT_BRANCH="${GIT_REF#refs/heads/}"
    CLEAN_GIT_BRANCH=$(echo "$GIT_BRANCH" | sed 's,/,_,g')
    if [ -n "$JENKINS_URL" ]; then
        GIT_SHORT_ID="$(git rev-parse --short HEAD)"
        BUILD_BASENAME="tails-${LB_ARCHITECTURE}-${CLEAN_GIT_BRANCH}-${AMNESIA_VERSION}-${AMNESIA_NOW}-${GIT_SHORT_ID}"
    else
        BUILD_BASENAME="tails-${LB_ARCHITECTURE}-${CLEAN_GIT_BRANCH}-${AMNESIA_VERSION}-${AMNESIA_TODAY}"
    fi
else
    GIT_CURRENT_COMMIT="$(git rev-parse HEAD)"
    if GIT_TAG="$(git describe --tags --exact-match ${GIT_CURRENT_COMMIT})"; then
        CLEAN_GIT_TAG=$(echo "$GIT_TAG" | sed 's,/,_,g')
	BUILD_BASENAME="tails-${LB_ARCHITECTURES}-${CLEAN_GIT_TAG}"
    else
	# this shouldn't reasonably happen (e.g. only if you checkout a
        # tag, remove the tag and then build)
	fatal "Neither a Git branch nor a tag, exiting."
    fi
fi

case "$LB_BINARY_IMAGES" in
   iso)
      BUILD_FILENAME_EXT=iso
      BUILD_FILENAME=binary
      ;;
   iso-hybrid)
      BUILD_FILENAME_EXT=iso
      BUILD_FILENAME=binary-hybrid
      ;;
   tar)
      BUILD_FILENAME_EXT=tar.gz
      BUILD_FILENAME=binary-tar
      ;;
   usb-hdd)
      BUILD_FILENAME_EXT=img
      BUILD_FILENAME=binary
      ;;
   *)
      fatal "Image type ${LB_BINARY_IMAGES} is not supported."
      ;;
esac
BUILD_DEST_FILENAME="${BUILD_BASENAME}.${BUILD_FILENAME_EXT}"
BUILD_MANIFEST="${BUILD_DEST_FILENAME}.list"
BUILD_PACKAGES="${BUILD_DEST_FILENAME}.packages.live"
BUILD_LOG="${BUILD_DEST_FILENAME}.buildlog"

echo "Building $LB_BINARY_IMAGES image ${BUILD_BASENAME}..."
set -o pipefail
time eatmydata lb build noauto ${@} 2>&1 | tee "${BUILD_LOG}"
RET=$?
if [ -e "${BUILD_FILENAME}.${BUILD_FILENAME_EXT}" ]; then
   if [ "$RET" -eq 0 ]; then
      echo "Image was successfully created"
   else
      echo "Warning: image created, but lb build exited with code $RET"
   fi
   echo "Renaming generated files..."
   mv -i "${BUILD_FILENAME}.${BUILD_FILENAME_EXT}" "${BUILD_DEST_FILENAME}"
   mv -i binary.packages "${BUILD_PACKAGES}"
else
   fatal "lb build failed ($?)."
fi
