#!/usr/bin/python3

import os
import re
import sh
import shutil
import tempfile

import tailslib.utils

print("Installing AppArmor profile for Tor Browser")

def binary_source_lines(source):
    with open(source, 'r') as f:
        return [line for line in f.read().splitlines()
                if not re.fullmatch(r'deb\s+file:/root/local-packages\s+\./',
                                    line)
                and re.match(r'deb\s', line)]


def toggle_src_APT_sources(mode):
   temp_apt_source = '/etc/apt/sources.list.d/tmp-deb-src.list'
   if mode:
       with open(temp_apt_source, 'a') as f:
           for source in ['/etc/apt/sources.list'] + \
                          sh.glob('/etc/apt/sources.list.d/*.list'):
               for line in binary_source_lines(source):
                   f.write(re.sub(r'^deb(\s+)', r'deb-src\1', line) + "\n")
   else:
         os.remove(temp_apt_source)
   sh.apt_get('--yes', 'update')


def install_torbrowser_AppArmor_profile(target):
   with tempfile.TemporaryDirectory() as tempdir:
      with tailslib.utils.chdir(tempdir):
          sh.apt_get('source', 'torbrowser-launcher/testing')
          profile = sh.glob("torbrowser-launcher-*/apparmor/torbrowser.Browser.firefox")[0]
          shutil.move(profile, target)
          os.chmod(target, 0o0644)


patch_path = '/usr/share/tails/torbrowser-AppArmor-profile.patch'
global_profile_path = '/etc/apparmor.d/torbrowser'
toggle_src_APT_sources(True)
install_torbrowser_AppArmor_profile(global_profile_path)
toggle_src_APT_sources(False)
with open(patch_path, 'r') as f:
    sh.patch('--forward', '--batch',  global_profile_path, _in = f.read())
os.remove(patch_path)
