#!/bin/sh

set -e
set -u

# This script runs the few steps required for windows 8 camouflage that cannot
# be run as the desktop user. It consists mainly of ugly workarounds. Running this
# script will change the system until next reboot.

# Import the TBB_INSTALL variable
. /usr/local/lib/tails-shell-library/tor-browser.sh

# Activate the camouflage for the next session
install -m 0644 \
    /usr/share/applications/tails-activate-win8-theme.desktop \
    /etc/xdg/autostart/

# Setup pidgin application icon (show in the windows list)
# The path to /usr/share/icons/hicolor is hardcoded in pidgin.
for icon in /usr/share/icons/hicolor/*/apps/pidgin.png; do
    rm "$icon"
    ln -s "/usr/share/icons/Windows8/apps/pidgin.png" "$icon"
done

# Set Tor Browser application icon
for icon in "${TBB_INSTALL}"/browser/chrome/icons/default/*.png \
    "${TBB_INSTALL}"/browser/icons/*.png; do
   rm "$icon"
   ln -s "/usr/share/icons/Windows8/apps/iceweasel.png" "$icon"
done

# Set florence virtual keyboard tray icon
ln -s "/usr/share/icons/Windows8/devices/input-keyboard-symbolic.png" \
    "/usr/share/pixmaps/florence.png"

# Set gpgApplet tray icon
rm "/usr/share/pixmaps/gpgApplet/scalable" -r
ln -s "/usr/share/pixmaps/gpgApplet/scalable-grey" "/usr/share/pixmaps/gpgApplet/scalable"
rm "/usr/share/pixmaps/gpgApplet/48x48/" -r
ln -s "/usr/share/pixmaps/gpgApplet/48x48-grey" "/usr/share/pixmaps/gpgApplet/48x48"

# For applications that support it, avoid showing splash screens:
for x in gimp scribus ; do
    dpkg-divert --add --rename --divert "/usr/bin/${x}-real" "/usr/bin/${x}"
    cat > "/usr/bin/${x}" <<_EOF
#!/bin/sh
"/usr/bin/${x}-real" --no-splash "\$@"
_EOF
    chmod 755 "/usr/bin/${x}"
done

# LibreOffice uses a different option name:
dpkg-divert --add --rename --divert /usr/bin/soffice-real /usr/bin/soffice
cat > /usr/bin/soffice <<_EOF
#!/bin/sh
/usr/bin/soffice-real --no-logo "\$@"
_EOF
chmod 755 /usr/bin/soffice

# Early set some gsettings
# Only setting all of them in this script fails
# Icon theme
sudo -u "$LIVE_USERNAME" gsettings set org.gnome.desktop.interface icon-theme Windows8
